### ISSUE TITLE
Looks in wrong place for requirements.txt

### ISSUE THREAD

**Issue by rossobianero** [ahmad-einieh/python-packages-handler#1]
I open my requirement.txt file for editing. Then I right click on the requirement I would like to install, and click “install Python packages “this opens a terminal which executes the command “pip install -r requirements —upgrade.”

 I then get an error “no such file or directory requirements.txt “. This is because the terminal has been opened in my user home directory, *not* the target directory where the file is. I’m running visual studio code 1.95.2 on Windows. 

I love the idea of this extension, and I really want to use it, but unfortunately it does not work for me.

**Comment by ahmad-einieh** [comment]
Thank you for your message. I have fixed the problem and improved the extension. Please update the extension to see the changes. I also have other ideas for further improvements that I will add later.
